### ISSUE TITLE
No longer builds

### ISSUE THREAD

**Issue by hoodie** [withoutboats/cargo-add#6]
Hi, I just tried to install this, but since the dependency versions aren't `"*"` it no longer builds with the current version of toml

**Comment by Henning-K** [comment]
Downgrading/Pinning toml-rs to version "0.2" instead of "*" should probably fix the error as 0.2.1 -> 0.3 was basically a complete rewrite and the API changed drastically because they now support Serde instead of rustc-serialize.
[Relevant Release note](https://github.com/alexcrichton/toml-rs/releases/tag/0.3.0)

EDIT: Maybe it would be a good idea to fix the versions of all the dependencies to known working ones so as to prevent this kind of breakage in the future.

**Comment by withoutboats** [comment]
I'll push a new version of this to crates.io with a corrected toml, but this crate is deprecated in favor of [killercup/cargo-edit](https://github.com/killercup/cargo-edit), which does the same thing better.

**Comment by withoutboats** [comment]
Uploaded a new version which builds on versions 1.15 & 1.14; also marked it as deprecated in the readme and the description.
